# -*- coding: utf-8 -*-
"""struct-to-dict. py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb-_waW-zE016Qc3Y1Tg5rNvKGRG6-8g
"""

from dataclasses import dataclass, asdict

@dataclass
class Student:
    name: str
    roll_no: int
    course: str

student = Student("Aman", 101, "Python")
student_dict = asdict(student)

print(student_dict)